image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo ENVIRONMENT=dev > .env
      pip install -r requirements.txt
      pip install -r dev-requirements.txt
      pip install -r test-requirements.txt
    command: |
      watchmedo auto-restart -d . -p "*.py;**/*.py" -R python main.py
  - command: |
      echo open $(gp url 8081)/test/#/frontend to test nonebot!

ports:
  - port: 3000-8999
    onOpen: ignore
    
vscode:
  extensions:
    - codezombiech.gitignore@0.6.0:bt7z8Cdl9iHzv1Swj1aDcw==
    - hbenl.vscode-test-explorer@2.19.4:k1U5F1c2ZouPEM4l6r4jDg==
    - littlefoxteam.vscode-python-test-adapter@0.6.5:M/0xh/MNGJTptXts7fD1Ug==