version: '3.4'

services:
  damebot:
    image: damebot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PYTHONASYNCIODEBUG=1
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 main.py "]
    ports:
      - 8081:8081
